package com.trabalho.sd.modelo.enums;

public enum EnumChannel {

    VISAO_PARA_CONTROLEE, VISAO_PARA_VISAO, 
    
    CONTROLE_PARA_VISAO, CONTROLE_PARA_MODELO, CONTROLE_PARA_CONTROLE, 
    
    MODELO_PARA_CONTROLE, MODELO_PARA_MODELO;

}
